system/framework/com.google.android.maps.jar
system/framework/com.google.android.media.effects.jar
system/framework/com.google.widevine.software.drm.jar
system/tts/lang_pico/es-ES_ta.bin
system/tts/lang_pico/it-IT_ta.bin
system/tts/lang_pico/it-IT_cm0_sg.bin
system/tts/lang_pico/de-DE_ta.bin
system/tts/lang_pico/de-DE_gl0_sg.bin
system/tts/lang_pico/es-ES_zl0_sg.bin
system/tts/lang_pico/fr-FR_nk0_sg.bin
system/tts/lang_pico/fr-FR_ta.bin
system/etc/permissions/com.google.widevine.software.drm.xml
system/etc/permissions/com.google.android.media.effects.xml
system/etc/permissions/features.xml
system/etc/permissions/com.google.android.maps.xml
system/etc/g.prop
system/etc/preferred-apps/google.xml
system/usr/srec/en-US/endpointer_dictation.config
system/usr/srec/en-US/g2p_fst
system/usr/srec/en-US/acoustic_model
system/usr/srec/en-US/hotword_symbols
system/usr/srec/en-US/compile_grammar.config
system/usr/srec/en-US/dict
system/usr/srec/en-US/clg
system/usr/srec/en-US/rescoring_lm
system/usr/srec/en-US/endpointer_voicesearch.config
system/usr/srec/en-US/metadata
system/usr/srec/en-US/embed_phone_nn_model
system/usr/srec/en-US/google_hotword_clg
system/usr/srec/en-US/phonelist
system/usr/srec/en-US/contacts.abnf
system/usr/srec/en-US/symbols
system/usr/srec/en-US/normalizer
system/usr/srec/en-US/google_hotword.config
system/usr/srec/en-US/ep_acoustic_model
system/usr/srec/en-US/lintrans_model
system/usr/srec/en-US/hmmsyms
system/usr/srec/en-US/grammar.config
system/usr/srec/en-US/dictation.config
system/usr/srec/en-US/norm_fst
system/usr/srec/en-US/google_hotword_logistic
system/usr/srec/en-US/c_fst
system/usr/srec/en-US/embed_phone_nn_state_sym
system/usr/srec/en-US/offensive_word_normalizer
system/lib/libfilterpack_facedetect.so
system/lib/libgtalk_jni.so
system/lib/libjni_latinime.so
system/lib/libfrsdk.so
system/lib/libpatts_engine_jni_api.so
system/lib/libgoogle_recognizer_jni.so
system/lib/libvorbisencoder.so
system/lib/libgcomm_jni.so
system/lib/libgtalk_stabilize.so
system/lib/libspeexwrapper.so
system/addon.d/70-gapps.sh
system/app/Talkback.apk
system/app/GoogleLoginService.apk
system/app/Phonesky.apk
system/app/GoogleContactsSyncAdapter.apk
system/app/SetupWizard.apk
system/app/OneTimeInitializer.apk
system/app/GooglePartnerSetup.apk
system/app/GoogleTTS.apk
system/app/MediaUploader.apk
system/app/LatinImeDictionaryPack.apk
system/app/ChromeBookmarksSyncAdapter.apk
system/app/GenieWidget.apk
system/app/VoiceSearchStub.apk
system/app/NetworkLocation.apk
system/app/ConfigUpdater.apk
system/app/QuickSearchBox.apk
system/app/GoogleBackupTransport.apk
system/app/GoogleCalendarSyncAdapter.apk
system/app/GmsCore.apk
system/app/Talk.apk
system/app/GoogleFeedback.apk
system/app/GoogleServicesFramework.apk
